name = "LikeC4"
grammar = "likec4"
path_suffixes = ["c4", "likec4", "like-c4"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
tab_size = 2

autoclose_before = "'\";:.,=}])> \n\t"

brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "'''", end = "'''", close = true, newline = true, not_in = ["string", "comment"] },
    { start = "\"\"\"", end = "\"\"\"", close = true, newline = true, not_in = ["string", "comment"] },
    { start = "/*", end = "*/", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "-[", end = "]->", close = true, newline = false },
]

word_characters = ["-", "_"]
